function aboutTopicMapping(docType='documents', hasTable = false, topicSize='total number of document parts'){
    let tableDetail = hasTable ? 
        `<p>Clicking on a topic provides a list documents ordered by topic proportion.
        Thus, continuing the example above, <i>topic 6</i>’s list would equal:
        <i>document b</i>, <i>a</i>, and other documents.</p>` : '';
    
    let docTypeDetail = docType == 'documents' ? '':
        ` (${docType})`;

    return `<p>This Map shows a set of "topics" that were generated by applying topic modelling [1,2,3] to the specified set of ${docType}.</p>
    <p>Topic Modelling calculates the distributions of these documents${docTypeDetail} over the topics.
    Thus, <i>document a</i> could be thought as combining <i>40% topic 3</i>, <i>35% topic 6</i>, and <i>25% topic 11</i>;
    while <i>document b</i> may combine <i>70% topic 6</i> and <i>30% topic 13</i>.</p>
    <p>The size of a topic’s circle in the map represents the ${topicSize} allocated to that topic.
    The closer the topics are together on the map, the more likely they are to share documents.</p>
    ${tableDetail}
    <p>For an overview of Topic Modelling see <a href="https://oar.princeton.edu/jspui/bitstream/88435/pr1bv3w/1/OA_IntroductionProbabilisticTopicModels.pdf" target="_blank">David Blei's Introduction to Probabilistic Topic Models</a> [1].</p>
    <p>[1] Blei. 2012. Introduction to Probabilistic Topic Models. <i>Communications of the ACM</i></p>
    <p>[2] Blei, Ng, and Jordan. 2003. Latent Dirichlet Allocation. <i>Journal of Machine Learning Research</i></p>
    <p>[3] Griffiths and Steyvers. 2004. Finding Scientific Topics. <i>Proceedings of the National Academy of Sciences</i></p>
    <hr>
    <p>To generate topics, our system uses the <i><a href="https://stanfordnlp.github.io/CoreNLP/" target="_blank">Stanford CoreNLP</a></i> [4] and 
    <i><a href="http://mallet.cs.umass.edu" target="_blank">MALLET</a></i> [5] packages.
    Our map visualisation is created using <i><a href="http://graphics.uni-konstanz.de/publikationen/Goertler2018BubbleTreemapsUncertainty/index.html" target="_blank">Bubble Treemaps</a></i> [6].
    Our interface is built with <i><a href="https://d3js.org/" target="_blank">D3</a></i> [7].</p>
    <p>[4] Manning et al. 2014. The Stanford CoreNLP Natural Language Processing Toolkit. <i>Proceedings of the 52nd Annual Meeting of the Association for Computational Linguistics: System Demonstrations</i></p>
    <p>[5] McCallum. 2002. MALLET: A Machine Learning for Language Toolkit. <i><a href="http://mallet.cs.umass.edu" target="_blank">http://mallet.cs.umass.edu</a></i></p>
    <p>[6] Görtler et al. 2018. Bubble Treemaps for Uncertainty Visualization. <i>IEEE Transactions on Visualization and Computer Graphics</i></p>
    <p>[7] Bostock, Ogievetsky, and Heer. 2011. D3: Data Driven Documents. <i>IEEE Transactions on Visualization and Computer Graphics</i></p>`;
}

export {aboutTopicMapping};